# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sonar-cloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sync-to-hub:
    needs: sonar-cloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Sync to hugging face
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://haokey:$HF_TOKEN@huggingface.co/spaces/haokey/text-to-video main
